Update dependencies
opcr-io/policy pull request #188
Opened 2024-12-18 16:22 UTC by carabasdaniel

2024-12-19 18:40 UTC, gertd commented on go.work
> +go 1.22.8
Please use the latest compiler version `1.22.10`

2024-12-19 18:40 UTC, gertd commented on go.work
> +toolchain go1.23.2
Please use the latest compiler version `1.23.4`

2024-12-19 18:41 UTC, gertd requested changes
Please use the latest compiler versions

2025-01-08 16:10 UTC, ronenh approved these changes

2025-01-09 20:01 UTC, gertd approved these changes

2025-01-10 07:53 UTC, merged